# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

######################################################################
# Site Configuration Config
######################################################################

# Global Site Title
title: OICR-EVENTS TRC

description: > # this means to ignore newlines until "baseurl:"
  Site designed for OICR-EVENTS to post schedules of talks online during an event.

# Contact Information
email: webdev@oicr.on.ca

# the subpath of your site, e.g. /blog
baseurl: ""

# Default permalink for posts
permalink: /node/:year-:month-:day-:title.html

# Post excerpt tag https://jekyllrb.com/docs/posts/#post-excerpts
excerpt_separator: "<!--more-->"

######################################################################
# Collections setting. https://jekyllrb.com/docs/collections/
######################################################################

collections:
  # Default collections
  _images:
    output: true
  _pages:
    output: true
  _privateFiles:
    output: false
  _files:
    output: true
  _videos:
    output: true
  _weblinks:
    output: true
  _modules:
    output: true
  _emailtpl:
    output: false
  # Custom collections
  _about:
    output: true
  _projects:
    output: true
  _blogs:
    output: true
 
defaults:
  # Default
  - scope:
      path: ""
      type: _weblinks
    values:
      layout: weblinks
      permalink: '/weblinks/:name/'
      published: true
  - scope:
      path: ''
      type: _modules
    values:
      title: ''
      date_tdt: '2018-07-11T19:36:04.633Z'
      author: ''
      layout: default
      permalink: '/_modules/:name/'
      published: true
      isPublic_b: false
    required: []
    validate: {}
    labels:
      title: Title
      date_tdt: Date
      author: Author
      layout: Layout
      permalink: Permanent Link
      published: Published
      isPublic_b: Public
# Custom collections
  # ABOUT
  - scope:
      path: ""
      type: _pages
    values:
      layout: default
      permalink: /
      published: true
      isPublic_b: true
      about_txt: ""
      like_list:
        - like_txt: ""
        - like_txt: ""
        - like_txt: ""
    labels:
      layout: Layout
      permalink: Permanent Link
      published: Published
      isPublic_b: Public
      profileImg: Picture of me
      about_txt: Description
      like_list: List of interests
  # PROJECTS
  - scope:
      path: ""
      type: _pages
    values:
      layout: projects
      permalink: "/projects/"
      published: true
      isPublic_b: true
      project_list:
        - projectItm_list:
          - projectImg: ""
          - project_txt: ""
    labels:
      layout: Layout
      permalink: Permanent Link
      published: Published
      isPublic_b: Public
      projectImg: Cover art
      project_txt: Description
  # BLOG
  - scope:
      path: ""
      type: _pages
    values:
      layout: blog
      permalink: "/blog/"
      published: true
      isPublic_b: true
      blog_list:
        - blogItm_list:
          - blogImg: ""
          - title_txt: ""
          - preview_txt: ""
          - blog_link: ""
        - blogItm_list:
          - blogImg: ""
          - title_txt: ""
          - preview_txt: ""
          - blog_link: ""
        - blogItm_list:
          - blogImg: ""
          - title_txt: ""
          - preview_txt: ""
          - blog_link: ""
    labels:
      layout: Layout
      permalink: Permanent link
      published: Published
      isPublic_b: Public
      blog_list: List of blog posts
######################################################################
# Jekyll Environment Config
######################################################################

# ImageFile Path
imagePath: /assets/site/images/

# Build settings
markdown: kramdown

# Jekyll plugins ( also requires to add list in Gemfile )
plugins:

# Exclude these files when the site is generated.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - webpack.config.js
  - .eslint
  - package.json
  - npm-debug.log
  - vendor
  - docker-compose.yml
  - start.sh
  - start-build.sh
  - start-preview.sh

theme: jekyll-theme-minimal
