<!-- JavaScript -->
<script type="text/javascript" src="/assets/core/js/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="/assets/core/js/bootstrap-3.3.7.min.js"></script>
<script type="text/javascript" src="/assets/core/js/spamspan.js"></script>
<script type="text/javascript" src="/assets/site/js/app.js"></script>
<script type="text/javascript">
(function() 

{ var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = '//api.usersnap.com/load/0d6f4c37-0a2a-4906-85bb-abc8ae67e8e7.js'; 
var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); } 

)();
</script> 
